# .github/workflows/newsletter.yml

name: Send Daily AI Newsletter

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

  # Schedules the workflow to run automatically
  schedule:
    # Runs at 08:00 UTC every day. You can change the time here.
    - cron: '0 8 * * *'

jobs:
  build-and-send:
    # The type of virtual machine to run the job on
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up a Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Installs the dependencies from your requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Runs the Python script to send the newsletter
      - name: Run the newsletter script
        env:
          # This section securely loads your secrets as environment variables
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          AI_INTERESTS: ${{ secrets.AI_INTERESTS }}
          TARGET_AUDIENCE: ${{ secrets.TARGET_AUDIENCE }}
          NEWSLETTER_NAME: ${{ secrets.NEWSLETTER_NAME }}
        run: python src/main.py --once
